### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by Pristar4** [Pristar4/Project-Rts#10]
### UI 

- [x]  should have Main Menu
- [ ] Options Menu in Game which switches to UI Input Map from Game Input Map
- [ ] HUD for better Ingame
